FROM python:3.10-slim

WORKDIR /app

COPY ./server/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./server .

# Create storage directories
RUN mkdir -p storage/pos

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
